package nguye.cardatabase.domain;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

@Data
@Entity
public class Car {
    @Id
    // The @GeneratedValue annotation defines that the ID is automatically generated by the database
    // The AUTO type means that the JPA provider selects the best strategy for a particular database, and it is also
    // the default generation type.
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // The database columns are named according to class field naming convention by default. The @Column annotation
    // can also be used to define the column's name, length and whether it's nullable.
    private String brand, model, color, registrationNumber;
    private int modelYear, price;

    public Car(String brand, String model, String color, String registrationNumber, int modelYear, int price) {
        super();
        this.brand = brand;
        this.model = model;
        this.color = color;
        this.registrationNumber = registrationNumber;
        this.modelYear = modelYear;
        this.price = price;
    }

    public Car() {}
}
